export const FETCH_BOARD = "FETCH_BOARD"

export const ADD_BOARD = "ADD_BOARD"

export const DELETE_BOARD = "DELETE_BOARD"

export const UPDATE_BOARD = "UPDATE_BOARD"

export const CONFIRM_UPDATE_BOARD = "CONFIRM_UPDATE_BOARD"