export const FETCH_DATA = "FETCH_DATA"

export const FETCH_DATA_TYPE1 = "FETCH_DATA_TYPE1"
export const FETCH_DATA_TYPE2 = "FETCH_DATA_TYPE2"
export const FETCH_DATA_TYPE3 = "FETCH_DATA_TYPE3"

export const ADD_DATA_TYPE1 = "ADD_DATA_TYPE1"
export const ADD_DATA_TYPE2 = "ADD_DATA_TYPE2"
export const ADD_DATA_TYPE3 = "ADD_DATA_TYPE3"